### PR TITLE
Fix autojump not inheriting the correct PATH

### PR DESCRIPTION
**Pull request by seanfarley**

### CODE REVIEW

**Comment by sagartewari01** [comment]
What does the `AUTOJUMP_SOURCED` variable do? It isn't used anywhere else. Is it a xonsh builtin for xontribs?

**Comment by seanfarley** [comment]
It's there to conform with mimicking the sourcing of, for example, `autojump.bash`:

https://github.com/wting/autojump/blob/master/bin/autojump.bash#L1 

Without having it `autojump` fails:

```
sean@laptop ~ $ j pybay
Traceback (Most recent call last):
51 /Users/sean/Library/Python/3.7/lib/python/site-packages/xontrib/autojump.xsh j --> universal_newlines=True).strip()
395 /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py check_output --> **kwargs).stdout
487 /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py run --> output=stdout, stderr=stderr)
CalledProcessError: Command '['autojump', 'pybay']' returned non-zero exit status 1.
```

**Comment by sagartewari01** [comment]
Thanks for the fix.

**Comment by seanfarley** [comment]
Thanks!

**Pull request merged**
